title: My App
author:
  name: Me_User
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  MyApp description.

# Theme-specific settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Collections
collections:
  places:
    output: true
    permalink: /:collection/:name
    
show_excerpts: true
